name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: seamingly-creative-memory-book
  RUN_REGION: us-west2


jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: seamingly-creative-memory-book

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          npm i && npm run build
      - name: Deploy
        run: |-
          gcloud app deploy app.yaml